---

- name: Calculate debconf answer
  set_fact:
    ferm_register_debconf: |
      {% if (ferm | bool and (ferm_ignore_cap12s | bool or (ansible_local|d() and ansible_local.cap12s|d() and
             (not ansible_local.cap12s.enabled | bool or
              (ansible_local.cap12s.enabled | bool and 'cap_net_admin' in ansible_local.cap12s.list))))) %}
      yes{% else %}no{% endif %}
  when: ansible_os_family == "Debian"

- name: Configure ferm status in debconf
  debconf:
    name: 'ferm'
    question: 'ferm/enable'
    vtype: 'boolean'
    value: '{{ ferm_register_debconf }}'
  when: ansible_os_family == "Debian"

- name: Ensure ferm is installed
  yum: name=ferm state=present
  when: (ansible_os_family == "RedHat" and (ferm | bool))

- name: Ensure ferm is installed
  apt:
    name: 'ferm'
    state: 'latest'
    install_recommends: 'no'
  when: (ansible_os_family == "Debian" and (ferm | bool and (ferm_ignore_cap12s | bool or (ansible_local|d() and ansible_local.cap12s|d() and
         (not ansible_local.cap12s.enabled | bool or
          (ansible_local.cap12s.enabled | bool and 'cap_net_admin' in ansible_local.cap12s.list))))))

- name: Create configuration directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'adm'
    mode: '2750'
  with_items:
    - '{{ ferm_config_dir }}/ferm.d'
    - '{{ ferm_config_dir }}/filter-input.d'

- name: Configure ferm default variables
  template:
    src: 'etc/default/ferm.j2'
    dest: '/etc/default/ferm'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart ferm' ]
  when: ansible_os_family == "Debian"

- name: Configure main ferm config file
  template:
    src: 'etc/ferm/ferm.conf.j2'
    dest: '{{ ferm_config_file }}'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

- name: Allow SSH access from Ansible Controller
  template:
    src: 'etc/ferm/filter-input.d/ansible_controller.conf.j2'
    dest: '{{ ferm_config_dir }}/filter-input.d/10_ansible_controller.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

- name: Configure forwarding in ip(6)tables if enabled
  template:
    src: 'etc/ferm/ferm.d/10_forward.conf.j2'
    dest: '{{ ferm_config_dir }}/ferm.d/10_forward.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  notify: [ 'Restart ferm' ]

- name: Remove ip(6)tables rules if requested
  file:
    path: '{{ ferm_config_dir }}/ferm.d/{{ item.weight | default("50") }}_{{ item.filename | default(item.type + "_" + item.dport[0] | default("rules")) }}.conf'
    state: 'absent'
  with_flattened:
    - ferm_rules
    - ferm_group_rules
    - ferm_host_rules
    - ferm_dependent_rules
  when: ((item.type is defined and item.type) and
         ((item.dport is defined and item.dport) or (item.rules is defined and item.rules)) and
         (item.delete is defined and item.delete))

- name: Configure ip(6)tables rules
  template:
    src: 'etc/ferm/ferm.d/{{ item.type }}.conf.j2'
    dest: '{{ ferm_config_dir }}/ferm.d/{{ item.weight | default("50") }}_{{ item.filename | default(item.type + "_" + (item.dport[0] | default("rules"))) }}.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  with_flattened:
    - ferm_rules
    - ferm_group_rules
    - ferm_host_rules
    - ferm_dependent_rules
  when: ((item.type is defined and item.type) and
         ((item.dport is defined and item.dport) or (item.rules is defined and item.rules)) and
         (item.delete is undefined or not item.delete))

- name: Remove iptables INPUT rules if requested
  file:
    path: '{{ ferm_config_dir }}/filter-input.d/{{ item.weight | default("50") }}_{{ item.filename | default(item.type + "_" + item.dport[0] | default("rules")) }}.conf'
    state: 'absent'
  with_flattened:
    - ferm_input_list
    - ferm_input_group_list
    - ferm_input_host_list
    - ferm_input_dependent_list
  when: ((item.type is defined and item.type) and
         ((item.dport is defined and item.dport) or (item.rules is defined and item.rules)) and
         (item.delete is defined and item.delete))

- name: Configure iptables INPUT rules
  template:
    src: 'etc/ferm/filter-input.d/{{ item.type }}.conf.j2'
    dest: '{{ ferm_config_dir }}/filter-input.d/{{ item.weight | default("50") }}_{{ item.filename | default(item.type + "_" + (item.dport[0] | default("rules"))) }}.conf'
    owner: 'root'
    group: 'adm'
    mode: '0644'
  with_flattened:
    - ferm_input_list
    - ferm_input_group_list
    - ferm_input_host_list
    - ferm_input_dependent_list
  when: ((item.type is defined and item.type) and
         ((item.dport is defined and item.dport) or (item.rules is defined and item.rules)) and
         (item.delete is undefined or not item.delete))

- name: Apply iptables rules if ferm is enabled
  command: ferm --slow {{ ferm_config_file }}
  changed_when: False
  when: (ferm | bool and (ferm_ignore_cap12s | bool or (ansible_local|d() and ansible_local.cap12s|d() and
         (not ansible_local.cap12s.enabled | bool or
          (ansible_local.cap12s.enabled | bool and 'cap_net_admin' in ansible_local.cap12s.list)))))

- name: Clear iptables rules if ferm is disabled
  command: ferm --flush {{ ferm_config_file }}
  changed_when: False
  when: ((not ferm and ferm_flush) and (ansible_local|d() and ansible_local.ferm|d() and
          ansible_local.ferm.enabled | bool) and (ferm_ignore_cap12s or (ansible_local|d() and ansible_local.cap12s|d() and
         (not ansible_local.cap12s.enabled or 'cap_net_admin' in ansible_local.cap12s.list))))

- name: Configure sysctl
  template:
    src: 'etc/sysctl.d/30-ferm.conf.j2'
    dest: '/etc/sysctl.d/30-ferm.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Reload sysctl' ]

- name: Configure forwarding in ifupdown if enabled
  template:
    src: 'etc/network/if-pre-up.d/ferm-forward.j2'
    dest: '/etc/network/if-pre-up.d/ferm-forward'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: ansible_os_family == "Debian"
  # TODO check if we should also have this on CentOS

- name: Ensure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save ferm local facts
  template:
    src: 'etc/ansible/facts.d/ferm.fact.j2'
    dest: '/etc/ansible/facts.d/ferm.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'

